# Generated by Django 3.2.5 on 2021-10-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehregister',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='vehregister',
            name='last_name',
        ),
        migrations.AddField(
            model_name='vehregister',
            name='dlugosc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10000),
        ),
        migrations.AddField(
            model_name='vehregister',
            name='dopuszczenie_pojazdu',
            field=models.CharField(choices=[('Pojazd ma dopuszczenie indywidualne europejskie WE', 'Euro'), ('Pojazd ma dopuszczenie jednostkowe', 'Jednostkowe')], default='Pojazd ma dopuszczenie indywidualne europejskie WE', max_length=200),
        ),
        migrations.AddField(
            model_name='vehregister',
            name='rodzaj_pojazdu',
            field=models.CharField(choices=[('Nowy', 'Nowy'), ('Uzywany', 'Uzywany'), ('Zabytkowy', 'Zabytkowy'), ('Samodzielnie zrobiony', 'Samodzielny')], default='Nowy', max_length=21),
        ),
        migrations.AddField(
            model_name='vehregister',
            name='rok_produkcji',
            field=models.DecimalField(decimal_places=0, default=2021, max_digits=4),
        ),
        migrations.AddField(
            model_name='vehregister',
            name='szerokosc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10000),
        ),
        migrations.AddField(
            model_name='vehregister',
            name='waga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10000),
        ),
        migrations.AddField(
            model_name='vehregister',
            name='wielkosc_zanurzenia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10000),
        ),
        migrations.AddField(
            model_name='vehregister',
            name='wysokosc_nad_poziomem_wody',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10000),
        ),
    ]
