# Generated by Django 3.2.8 on 2021-11-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj_pojazdu', models.CharField(choices=[('Nowy', 'Nowy'), ('Uzywany', 'Uzywany'), ('Zabytkowy', 'Zabytkowy'), ('Samodzielnie zrobiony', 'Samodzielny')], default='Nowy', max_length=21)),
                ('rok_produkcji', models.DecimalField(blank=True, decimal_places=0, default=2021, max_digits=4, null=True)),
                ('waga', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10000, null=True)),
                ('dlugosc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10000, null=True)),
                ('szerokosc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10000, null=True)),
                ('glebokosc_zanurzenia', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10000, null=True)),
                ('wysokosc_nad_poziomem_wody', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10000, null=True)),
                ('dopuszczenie_pojazdu', models.CharField(blank=True, choices=[('Pojazd ma dopuszczenie indywidualne europejskie WE', 'Pojazd ma dopuszczenie indywidualne europejskie WE'), ('Pojazd ma dopuszczenie jednostkowe', 'Pojazd ma dopuszczenie jednostkowe')], default='Pojazd ma dopuszczenie indywidualne europejskie WE', max_length=100, null=True)),
                ('dowod_potwierdzajacy_wlasnosc', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
