# Generated by Django 3.2.9 on 2021-11-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitioner_app', '0003_application_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='form',
        ),
    ]
