# Generated by Django 3.2.9 on 2021-11-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitioner_app', '0004_remove_application_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applicant',
            new_name='petitioner',
        ),
    ]
