# Generated by Django 3.2.9 on 2021-11-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitioner_app', '0005_rename_applicant_application_petitioner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehregister',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
