# Generated by Django 3.2.9 on 2021-11-14 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petitioner_app', '0006_alter_vehregister_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='petitioner_app.vehregister'),
            preserve_default=False,
        ),
    ]
